/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.beholder.metrorealm.ui;

import br.beholder.filecontrol.FilePicker;
import br.beholder.filecontrol.SimpleFileReader;
import br.beholder.metrorealm.core.FuzzyCalculator;
import br.beholder.metrorealm.ui.swing.webLaf.WeblafUtils;
import br.beholder.metrorealm.ui.utils.ColorController;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Alisson
 */
public class MainWindow extends javax.swing.JFrame {
    File custo;
    File input;
    File rules;
    File testcusto;
    File testinput;
    File testrules;
    FuzzyCalculator calculator;
    
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        WeblafUtils.instalaWeblaf();
        initComponents();
        try {
            imageJPanel1.setImage(ImageIO.read(new File("./src/br/beholder/resources/wall.jpg")));
        } catch (IOException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        setSize(new Dimension(1200, 720));
        setLocationRelativeTo(null);
        calculator = new FuzzyCalculator();
        testrules= new File("./src/br/beholder/metrorealm/resources/tipper.flc");
        testinput= new File("./amostras/itajai-navegantes/br/eficiencia.txt");
        testcusto= new File("./amostras/itajai-navegantes/br/custo.txt");
        
        custo = testcusto;
        custoname.setText(custo.getPath());
        custotext.setText(SimpleFileReader.getInstance().fileToString(custo));
        
        rules = testrules;
        rulesnome.setText(rules.getPath());
        rulesTExt.setText(SimpleFileReader.getInstance().fileToString(rules));
        
        input = testinput;
        inputnome.setText(input.getPath());
        inputtext.setText(SimpleFileReader.getInstance().fileToString(input));
        
        
        if(WeblafUtils.weblafEstaInstalado()){
            WeblafUtils.configuraWebLaf(media);
            WeblafUtils.configuraWebLaf(custotext);
            WeblafUtils.configuraWebLaf(inputtext);
            WeblafUtils.configuraWebLaf(rulesTExt);
            WeblafUtils.configuraWebLaf(custoname);
            WeblafUtils.configuraWebLaf(inputnome);
            WeblafUtils.configuraWebLaf(rulesnome);
            
            WeblafUtils.configuraWebLaf(jScrollPane1);
            WeblafUtils.configuraWebLaf(jScrollPane2);
            WeblafUtils.configuraWebLaf(jScrollPane3);

            WeblafUtils.configurarBotao(calcular);
            WeblafUtils.configurarBotao(custoButton);
            WeblafUtils.configurarBotao(inputButton);
            WeblafUtils.configurarBotao(rulesButton);
            WeblafUtils.configurarBotao(webButton1);
            
            jLabel2.setForeground(ColorController.COR_LETRA);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageJPanel1 = new br.beholder.metrorealm.ui.swing.webLaf.ImageJPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        custoButton = new com.alee.laf.button.WebButton();
        custoname = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        custotext = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inputtext = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        inputnome = new javax.swing.JTextField();
        inputButton = new com.alee.laf.button.WebButton();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        rulesTExt = new javax.swing.JTextArea();
        jPanel12 = new javax.swing.JPanel();
        rulesnome = new javax.swing.JTextField();
        rulesButton = new com.alee.laf.button.WebButton();
        jPanel4 = new javax.swing.JPanel();
        webButton1 = new com.alee.laf.button.WebButton();
        jPanel2 = new javax.swing.JPanel();
        calcular = new com.alee.laf.button.WebButton();
        media = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Similação Fuzzy de Rotas entre Cidades");

        imageJPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        imageJPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.BorderLayout(10, 0));

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.BorderLayout(0, 5));

        jPanel8.setOpaque(false);
        jPanel8.setLayout(new java.awt.BorderLayout(0, 5));

        custoButton.setText("custo");
        custoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custoButtonActionPerformed(evt);
            }
        });
        jPanel8.add(custoButton, java.awt.BorderLayout.NORTH);

        custoname.setText("jTextField1");
        jPanel8.add(custoname, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel8, java.awt.BorderLayout.NORTH);

        custotext.setColumns(20);
        custotext.setRows(5);
        jScrollPane1.setViewportView(custotext);

        jPanel7.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7, java.awt.BorderLayout.WEST);

        jPanel9.setOpaque(false);
        jPanel9.setLayout(new java.awt.BorderLayout(0, 5));

        inputtext.setColumns(20);
        inputtext.setRows(5);
        jScrollPane2.setViewportView(inputtext);

        jPanel9.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel10.setOpaque(false);
        jPanel10.setLayout(new java.awt.BorderLayout(0, 5));

        inputnome.setText("jTextField2");
        jPanel10.add(inputnome, java.awt.BorderLayout.CENTER);

        inputButton.setText("input");
        inputButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputButtonActionPerformed(evt);
            }
        });
        jPanel10.add(inputButton, java.awt.BorderLayout.PAGE_START);

        jPanel9.add(jPanel10, java.awt.BorderLayout.PAGE_START);

        jPanel3.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel11.setOpaque(false);
        jPanel11.setLayout(new java.awt.BorderLayout(0, 5));

        rulesTExt.setColumns(20);
        rulesTExt.setRows(5);
        jScrollPane3.setViewportView(rulesTExt);

        jPanel11.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel12.setOpaque(false);
        jPanel12.setLayout(new java.awt.BorderLayout(0, 5));

        rulesnome.setText("jTextField3");
        jPanel12.add(rulesnome, java.awt.BorderLayout.CENTER);

        rulesButton.setText("rules");
        rulesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rulesButtonActionPerformed(evt);
            }
        });
        jPanel12.add(rulesButton, java.awt.BorderLayout.PAGE_START);

        jPanel11.add(jPanel12, java.awt.BorderLayout.NORTH);

        jPanel3.add(jPanel11, java.awt.BorderLayout.EAST);

        imageJPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.BorderLayout(5, 0));

        webButton1.setText("testar");
        webButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(webButton1, java.awt.BorderLayout.LINE_START);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.BorderLayout(0, 5));

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });
        jPanel2.add(calcular, java.awt.BorderLayout.CENTER);
        jPanel2.add(media, java.awt.BorderLayout.NORTH);

        jPanel4.add(jPanel2, java.awt.BorderLayout.CENTER);

        imageJPanel1.add(jPanel4, java.awt.BorderLayout.SOUTH);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 20, 20, 20));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/beholder/metrorealm/resources/van.png"))); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Calculadora de Mobilidade");
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        imageJPanel1.add(jPanel1, java.awt.BorderLayout.NORTH);

        getContentPane().add(imageJPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void custoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custoButtonActionPerformed
        File buffer = FilePicker.chooseFile();;
        if(buffer == null){
            return;
        }
        custo = buffer;
        custoname.setText(custo.getPath());
        custotext.setText(SimpleFileReader.getInstance().fileToString(custo));
    }//GEN-LAST:event_custoButtonActionPerformed

    private void inputButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputButtonActionPerformed
        File buffer = FilePicker.chooseFile();;
        if(buffer == null){
            return;
        }
        input = buffer;
        inputnome.setText(input.getPath());
        inputtext.setText(SimpleFileReader.getInstance().fileToString(input));
    }//GEN-LAST:event_inputButtonActionPerformed

    private void rulesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rulesButtonActionPerformed
        File buffer = FilePicker.chooseFile();;
        if(buffer == null){
            return;
        }
        rules = buffer;
        rulesnome.setText(rules.getPath());
        rulesTExt.setText(SimpleFileReader.getInstance().fileToString(rules));
    }//GEN-LAST:event_rulesButtonActionPerformed

    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        media.setText(calculator.calculate(rules, input, custo)+"");
    }//GEN-LAST:event_calcularActionPerformed

    private void webButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webButton1ActionPerformed
        media.setText(calculator.calculate(testrules, testinput, testcusto,true)+"");
    }//GEN-LAST:event_webButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.alee.laf.button.WebButton calcular;
    private com.alee.laf.button.WebButton custoButton;
    private javax.swing.JTextField custoname;
    private javax.swing.JTextArea custotext;
    private br.beholder.metrorealm.ui.swing.webLaf.ImageJPanel imageJPanel1;
    private com.alee.laf.button.WebButton inputButton;
    private javax.swing.JTextField inputnome;
    private javax.swing.JTextArea inputtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField media;
    private com.alee.laf.button.WebButton rulesButton;
    private javax.swing.JTextArea rulesTExt;
    private javax.swing.JTextField rulesnome;
    private com.alee.laf.button.WebButton webButton1;
    // End of variables declaration//GEN-END:variables
}
